export enum NotificationEvent {
  BOOKING_REQUESTED = 'BOOKING_REQUESTED',
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  DRIVER_ASSIGNED = 'DRIVER_ASSIGNED',
  DRIVER_EN_ROUTE = 'DRIVER_EN_ROUTE',
  DRIVER_ARRIVED = 'DRIVER_ARRIVED',
  TRIP_COMPLETED = 'TRIP_COMPLETED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  FLIGHT_UPDATED = 'FLIGHT_UPDATED',
  NEW_TRIP_AVAILABLE = 'NEW_TRIP_AVAILABLE',
  PICKUP_SOON = 'PICKUP_SOON',
  DOCUMENT_EXPIRING = 'DOCUMENT_EXPIRING',
  INVOICE_READY = 'INVOICE_READY',
  UNASSIGNED_BOOKING = 'UNASSIGNED_BOOKING',
}

export enum NotificationChannel {
  PUSH = 'PUSH',
  SMS = 'SMS',
  EMAIL = 'EMAIL',
  WHATSAPP = 'WHATSAPP',
}

export enum NotificationStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
}

export enum RecipientRole {
  PASSENGER = 'PASSENGER',
  DRIVER = 'DRIVER',
  ADMIN = 'ADMIN',
  CORPORATE = 'CORPORATE',
}

export enum NotificationLanguage {
  EN = 'en',
  BN = 'bn',
}
